version: '3.2'
volumes:
  postgres-data:
  redis-data:
  bundle-cache:
services:
  web:
    container_name: accounts_web
    build:
      context: .
      dockerfile: ./config/docker/dev/Dockerfile
    image: accounts/api
    environment:
    - RAILS_ENV=development
    - EDITOR=vim
    - THOR_MERGE=vim
    ports:
    - "3024:3000"
    depends_on:
    - db
    volumes:
    - .:/app
    - bundle-cache:/bundle
    stdin_open: true
    tty: true
  db:
    container_name: accounts_db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5487:5432"
